/**
 * scripts/gen-worker.mjs
 *
 * Generates dist/_worker.js for local `wrangler pages dev`.
 *
 * Why this exists:
 *   Wrangler normally compiles functions/ with esbuild. In Yarn PnP
 *   environments the esbuild process cannot resolve wrangler's own internal
 *   dependency `path-to-regexp` because the PnP manifest was built without it.
 *   Writing a pre-compiled _worker.js bypasses the esbuild step entirely
 *   (Cloudflare Pages "Advanced Mode"). dist/ is gitignored so this file is
 *   never seen by Cloudflare Pages CI, which compiles functions/ normally.
 *
 * Usage:
 *   npm run build          # produces dist/
 *   npm run pages:dev      # runs this script, then starts wrangler
 */

import { existsSync, writeFileSync } from "node:fs";

if (!existsSync("dist")) {
  console.error(
    "[gen-worker] dist/ not found — run `npm run build` first, then retry `npm run pages:dev`.",
  );
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Worker source — mirrors the validation logic in functions/api/contact.ts.
// Any change to the validation rules must be kept in sync with contact.ts.
// ---------------------------------------------------------------------------
const workerSrc = `// dist/_worker.js — generated by scripts/gen-worker.mjs
// Do not edit by hand. Edit scripts/gen-worker.mjs or functions/api/contact.ts instead.

const JSON_HEADERS = {
  "Content-Type": "application/json; charset=utf-8",
  "Cache-Control": "no-store",
};

function jsonResponse(status, body) {
  return new Response(JSON.stringify(body), { status, headers: JSON_HEADERS });
}

async function handleContactPost(request) {
  let body;
  try {
    body = await request.json();
  } catch {
    return jsonResponse(400, { ok: false, message: "Bitte prüfen Sie Ihre Angaben." });
  }

  const name    = String(body.name    ?? "").trim();
  const phone   = String(body.phone   ?? "").trim();
  const email   = String(body.email   ?? "").trim();
  const message = String(body.message ?? "").trim();
  const privacy = body.privacy;
  const website = String(body.website ?? "").trim();

  // Honeypot: silently succeed without logging content
  if (website) {
    return jsonResponse(200, { ok: true, message: "Vielen Dank. Wir melden uns zeitnah bei Ihnen." });
  }

  // Validation
  if (!name || !message || (!phone && !email) || privacy !== true) {
    return jsonResponse(400, { ok: false, message: "Bitte prüfen Sie Ihre Angaben." });
  }

  // Log minimal diagnostic summary — never log actual personal data
  console.log(
    \`[contact mock] accepted request: namePresent=true phonePresent=\${Boolean(phone)} emailPresent=\${Boolean(email)} messageLength=\${message.length}\`,
  );

  return jsonResponse(200, { ok: true, message: "Vielen Dank. Wir melden uns zeitnah bei Ihnen." });
}

export default {
  async fetch(request, env) {
    const url = new URL(request.url);

    if (url.pathname === "/api/contact") {
      if (request.method !== "POST") {
        return jsonResponse(405, { ok: false, message: "Method not allowed." });
      }
      return handleContactPost(request);
    }

    // All other routes: serve static assets from dist/
    return env.ASSETS.fetch(request);
  },
};
`;

writeFileSync("dist/_worker.js", workerSrc, "utf8");
console.log("[gen-worker] dist/_worker.js written — wrangler will use Advanced Mode (no esbuild on functions/)");
